services:
  nginx:
    image: nginx:1.24-alpine
    restart: unless-stopped
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/ssl:/etc/nginx/ssl
      - ./volumes/www:/www
